More of various improvements
kinvolk/flatcar-linux-update-operator pull request #56
Opened 2020-11-22 18:41 UTC by invidian

2020-12-10 23:18 UTC, invidian commented
Finally I got a minute to come back to it, as few days ago I started reviewing it myself and I didn't really like the diff in the commits, so had to re-organize things a bit to make it a bit easier to understand.

2020-12-11 04:54 UTC, knrt10 requested changes
Small NIT, rest LGTM, nice work

2020-12-11 04:54 UTC, knrt10 commented on pkg/operator/operator.go
> +			}
can we simplify it with if else?

2020-12-11 08:16 UTC, invidian commented on pkg/operator/operator.go
> +			}
I found even better way. I'll take `string` instead of `bool` as a parameter, so I can pass `constants.True` or `constants.False` to the function directly to remove indirection AND a `bool` parameter :tada:

2020-12-11 09:00 UTC, knrt10 requested changes
Would be better like this I guess

2020-12-11 09:00 UTC, knrt10 commented on pkg/operator/operator.go
> +func (k *Kontroller) checkReboot(req *labels.Requirement, annotations []string, label string, okToReboot string) error {
```suggestion
func (k *Kontroller) checkReboot(req *labels.Requirement, annotations []string, label, okToReboot string) error {
```

2020-12-11 09:03 UTC, invidian commented on pkg/operator/operator.go
> +func (k *Kontroller) checkReboot(req *labels.Requirement, annotations []string, label string, okToReboot string) error {
Yes, thanks, fixed!

2020-12-11 09:14 UTC, knrt10 approved these changes

2020-12-11 09:15 UTC, merged